### ISSUE TITLE
many falty

### ISSUE THREAD

**Issue by manuel76413** [KambizAsadzadeh/Platform-Detector#1]
detect windows info in program,

_WIN32 is present in both 32 bit and 64 bit Windows Operating System, we need to first check the presence of _WIN32 to confirm that it is a Windows Operating System and then, check the presence of _WIN64 to confirm whether it is a 64 bit Windows Operating System or a 32 bit Windows Operating System.

use your code , always return x86(32-bit) even in X64 configuration

**Comment by thecompez** [comment]
Thank you for attention, The problem was solved.

https://github.com/KambizAsadzadeh/Platform-Detector/commit/f5d6174656cb519c49a28eafe72b52cf59ced977
